-- FINDING TOP 10 SELLING COUNTIES FOR ALL ALCOHOL CATEGORIES
SELECT c.county,c.population, COUNT(s.item),SUM(s.total) AS Total
FROM sales s
INNER JOIN counties c
ON c.county = s.county
GROUP BY 1
ORDER BY 2, 3
;
--FINDING TOP 100 SELLING VENDORS IN EACH COUNTY
SELECT  DISTINCT p.Vendor_name, c.county, SUM(s.total) AS Total
FROM sales s
INNER JOIN  counties c
ON s.county= c.county
LEFT JOIN products p
ON p.item_no = s.item
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 100
;
--FINDING TOP SELLING ITEMS BY VENDORS IN POLK COUNTY
SELECT DISTINCT p.Vendor_name, st.Name, COUNT(s.item) AS Total_Items_Sold
FROM sales s
INNER JOIN  counties c
ON s.county= c.county
LEFT JOIN products p
ON p.item_no = s.item
LEFT JOIN stores st
ON st.store = s.store
WHERE c.county ILIKE '%black%' AND c.county ILIKE '%hawk%'
GROUP BY 1, 2
ORDER BY 3 DESC
;
--FINDING TOP SELLING (ACTIVE) STORES IN POLK COUNTY
SELECT DISTINCT

-- FINDING THE TOP CATEGORIES IN EACH COUNTY

--FINDING VENDORS WITH TOP SELLING UNTIS AND REVENUE
SELECT DISTINCT VENDOR, SUM(TOTAL), COUNT(ITEM)
FROM SALES
GROUP BY 1
ORDER BY 2 DESC
;
--DIAGEO AMERICAS TOP SELLING COUNTIES AND STORES
SELECT C.COUNTY, ST.NAME, S.CATEGORY_NAME, SUM(S.TOTAL)
FROM SALES S
LEFT JOIN COUNTIES C
ON C.COUNTY = S.COUNTY
LEFT JOIN STORES ST
ON S.STORE= ST.STORE
WHERE S.VENDOR ILIKE '%DIAGEO%'
GROUP BY 1, 2, 3
ORDER BY 4 DESC
;
--AVG BTL PRICE PER COUNTY COMPARED WITH TOTAL
SELECT COUNTIES.COUNTY, VENDOR, AVG(BTL_PRICE::NUMERIC),COUNT(ITEM), SUM(TOTAL)
FROM SALES
LEFT JOIN COUNTIES
ON SALES.COUNTY= COUNTIES.COUNTY
GROUP BY 1, 2
ORDER BY 3, 4, 5 DESC
;
--LUXCO ST LOUIS SEEMS TO SELL THE MOST UNITS OF ALL THE BRANDS BUT HAS A LOWER BTL PRICE
--AVG BTL PRICE PER COUNTY COMPARED WITH TOTAL FOR DIAGEO ALONE
SELECT COUNTIES.COUNTY, AVG(BTL_PRICE::NUMERIC),COUNT(ITEM), SUM(TOTAL)
FROM SALES
LEFT JOIN COUNTIES
ON SALES.COUNTY= COUNTIES.COUNTY
WHERE SALES.VENDOR ILIKE '%DIAGEO%'
GROUP BY 1
ORDER BY 2,3, 4
;
--COST OF DIAGEO PRODUCTS COMPARED WITH UNITS SOLD AND TOTAL TO SEE IF SOME PRODUCTS ARE TOO EXPENSIVE TO BE POPULAR
SELECT s.CATEGORY_NAME
FROM SALES S
left join PRODUCTS P
ON S.ITEM = P.ITEM_NO
WHERE P.VENDOR  ILIKE '%DIAGEO%'
;
SELECT DISTINCT S.Category_name, SUM(S.TOTAL)
FROM Sales s
LEFT JOIN Products p
ON s.item = p.item_no
WHERE s.vendor ILIKE '%DIAGEO%'
GROUP BY 1
ORDER BY 2 DESC
;
--CATEGGORIES AND ITEM DESCRIPTIONS AND UNITS SOLD
SELECT DISTINCT S.Category_name, P.ITEM_DESCRIPTION, COUNT(S.ITEM)
FROM Sales s
LEFT JOIN Products p
ON s.item = p.item_no
WHERE s.vendor ILIKE '%DIAGEO%'
GROUP BY 1, 2
ORDER BY 3 DESC
;
--LUXCOS TOP COUNTY
SELECT C.COUNTY, ST.NAME, S.CATEGORY_NAME, SUM(S.TOTAL)
FROM SALES S
LEFT JOIN COUNTIES C
ON C.COUNTY = S.COUNTY
LEFT JOIN STORES ST
ON S.STORE= ST.STORE
WHERE S.VENDOR ILIKE '%LUXCO%'
GROUP BY 1, 2, 3
ORDER BY 4 DESC
;
---TOP SELLING ITEMS FROM DIAGEO
SELECT DISTINCT P.ITEM_DESCRIPTION, SUM(S.TOTAL)
FROM Sales s
LEFT JOIN Products p
ON s.item = p.item_no
WHERE s.vendor ILIKE '%DIAGEO%'
GROUP BY 1
ORDER BY 2 DESC
;
--DIAGEO SALES FROM CONVEINENCE STORES
SELECT DISTINCT P.ITEM_DESCRIPTION,
CASE
WHEN S.CONVENIENCE_STORE ILIKE 'Y'
THEN 1 ELSE 0 END AS CONVENIENCE
FROM SALES S
LEFT JOIN PRODUCTS P
ON P.ITEM_NO = S.ITEM
WHERE S.VENDOR ILIKE '%DIAGEO%'
;
-EXPLORING DATES
SELECT MIN(DATE), MAX(DATE)
FROM SALES
;
--IN CLASS PRACTICE
SELECT
       DATE_PART(‘MM’,date)
, sum(total)
from sales
group by 1
order by 1
;
--SALES BETWEEN
SELECT COUNT(ITEM)
FROM SALES
WHERE DATE BETWEEN '2014-05-01' AND '2014-8-28'
;
---SALES SEPERATED BY STORE AND PRODUCTS SOLD AND TOTAL
SELECT ST.NAME, COUNT(S.ITEM), AVG(S.TOTAL), SUM(S.TOTAL)
FROM SALES S
LEFT JOIN STORES ST
ON S.STORE = ST.STORE
GROUP BY 1
ORDER BY 2, 3,4
;
--LIST DATE FOR PRODUCTS TO FIND NEWEST AND OLDEST PRODUCTS
SELECT MIN(LIST_DATE::TIMESTAMP)
FROM PRODUCTS
;
--DIAGEOS FULL PRODUCT COUNT
SELECT COUNT(DISTINCT P.ITEM_DESCRIPTION)
FROM PRODUCTS P
LEFT JOIN SALES S
ON P.ITEM_NO = S.ITEM
WHERE S.VENDOR ILIKE '%DIAGEO%'
;
--STORE LIST FOR TOP DIAGEO SALES
SELECT DISTINCT ST.NAME, C.COUNTY, ST.STORE_STATUS, S.CONVENIENCE_STORE, SUM(S.TOTAL)
FROM SALES S
INNER JOIN STORES ST
ON ST.STORE = S.STORE
LEFT JOIN COUNTIES C
ON C.COUNTY = S.COUNTY
WHERE S.VENDOR ILIKE '%DIAGEO%'
GROUP BY 1, 2, 3, 4
ORDER BY 5
;
--NUMBER OF STORES BY COUNTY
SELECT C.COUNTY, COUNT(DISTINCT ST.STORE), SUM(S.TOTAL)
FROM SALES S
LEFT JOIN COUNTIES C
ON C.COUNTY = S.COUNTY
LEFT JOIN STORES ST
ON ST.STORE = S.STORE
GROUP BY 1
ORDER BY 2, 3
;
--LIST OF STORES IN COUNTIES WITH MORE THAN 20 STORES
SELECT C.COUNTY, COUNT(DISTINCT ST.STORE), SUM(S.TOTAL)
FROM SALES S
LEFT JOIN COUNTIES C
ON C.COUNTY = S.COUNTY
LEFT JOIN STORES ST
ON ST.STORE = S.STORE
 GROUP BY 1
HAVING COUNT(DISTINCT ST.STORE) >20
ORDER BY 2, 3
;
--items pricing
SELECT ITEM_DESCRIPTION, (CAST BOTTLE_PRICE AS NUMERIC)AS BOTTLEPRICE
FROM PRODUCTS
WHERE VENDOR ILIKE '%DIAGEO%'
;
--TOTAL ITEMS FOR  FOR DIAGEO
SELECT COUNT(DISTINCT ITEM)
FROM SALES
GROUP BY VENDOR
HAVING VENDOR ILIKE '%DIAGEO%'
ORDER BY 1
;
--finding number of store per county convenience vs big box
SELECT
CASE WHEN S.CONVENIENCE C.COUNTY, COUNT(DISTINCT ST.STORE), SUM(S.TOTAL)
FROM SALES S
LEFT JOIN COUNTIES C
ON C.COUNTY = S.COUNTY
LEFT JOIN STORES ST
ON ST.STORE = S.STORE
GROUP BY 1
ORDER BY 2, 3
;

--POP
SELECT COUNTY, POPULATION
FROM COUNTIES
;
-VENDOR SALES
SELECT S.VENDOR, COUNT(DISTINCT S.ITEM) AS ITEMS_SOLD, COUNT(DISTINCT P.ITEM_NO) AS ITEMS_CARRIED
FROM SALES S
LEFT JOIN PRODUCTS P
ON P.ITEM_NO = S.ITEM
GROUP BY 1
ORDER BY 2
;
--ITEMS UNDER SPICED RUM AND DIAGEO
SELECT DISTINCT P.ITEM_DESCRIPTION, SUM(S.TOTAL)
FROM Sales s
LEFT JOIN Products p
ON s.item = p.item_no
WHERE s.vendor ILIKE '%DIAGEO%' AND S.CATEGORY_NAME ILIKE '%SPICED%'
GROUP BY 1
ORDER BY 2 DESC
;
--SALES THAT OCCURRED AT CONVENIENCE STORES
SELECT COUNT(ITEM),
       (SELECT COUNT(ITEM)
FROM SALES
WHERE CONVENIENCE_STORE = 'Y' AND VENDOR ILIKE '%DIAGEO%') AS CONVENIENCE
FROM SALES
WHERE VENDOR ILIKE '%DIAGEO%'
;
-- SALES AND TOTAL FROM HY VEE, WALMART AND SAMS CLUB
SELECT COUNT(DISTINCT S.ITEM), AVG(S.TOTAL), SUM(S.TOTAL)
FROM SALES S
LEFT JOIN STORES ST
ON ST.STORE = S.STORE
WHERE ST.NAME ILIKE '%WAL-MART%' OR ST.NAME ILIKE '%SAM%' AND ST.NAME ILIKE '%CLUB%' OR ST.NAME ILIKE '%HY%' AND ST.NAME ILIKE '%VEE%'
;
--
SELECT COUNT(S.ITEM), AVG(S.TOTAL), SUM(S.TOTAL)
FROM SALES S
LEFT JOIN STORES ST
ON ST.STORE = S.STORE
WHERE ST.NAME ILIKE  '%HY%' AND ST.NAME ILIKE '%VEE%'
;
SELECT C.COUNTY, COUNT(DISTINCT ST.NAME)
FROM SALES S
LEFT JOIN STORES ST
ON ST.STORE = S.STORE
LEFT JOIN COUNTIES C
ON S.COUNTY = C.COUNTY
WHERE ST.NAME ILIKE 'WAL-MART%'
GROUP BY 1
ORDER BY 2
;
--STORES IN EACH COUNT
SELECT C.COUNTY, AVG(S.TOTAL), COUNT(DISTINCT ST.STORE)
FROM SALES S
INNER JOIN STORES ST
    ON ST.STORE = S.STORE
INNER JOIN COUNTIES C
ON S.COUNTY = C.COUNTY
GROUP BY 1
ORDER BY 2, 3

;
---VENDORS
SELECT  p.Vendor_name, SUM(s.total) AS Total
FROM sales s
INNER JOIN  counties c
ON s.county= c.county
LEFT JOIN products p
ON p.item_no = s.item
GROUP BY 1
ORDER BY 2 DESC
;
SELECT DISTINCT VENDOR, SUM(TOTAL)
FROM SALES
GROUP BY 1
ORDER BY 2
;
--HY VEE SALES FOR DIAGEO
SELECT COUNT(S.ITEM), AVG(S.TOTAL), SUM(S.TOTAL)
FROM SALES S
LEFT JOIN STORES ST
ON ST.STORE = S.STORE
WHERE ST.NAME ILIKE  '%HY%' AND ST.NAME ILIKE '%VEE%' AND S.VENDOR ILIKE '%DIAGEO%'
;
--SALES BETWEEN QUARTERS
SELECT COUNT(ITEM)
FROM SALES
WHERE DATE BETWEEN '2015-01-01' AND '2015-01-31'
;
SELECT CASE WHEN S.DATE BETWEEN '2014-01-01' AND '2014-03-31' THEN 'Q1'
WHEN S.DATE BETWEEN '2014-04-01' AND '2014-06-30' THEN 'Q2'
    WHEN S.DATE BETWEEN '2014-07-01' AND '2014-09-30' THEN 'Q3'
    WHEN S.DATE BETWEEN '2014-10-01' AND '2014-12-31' THEN 'Q4'
        ELSE 'Q2015' END,
COUNT(ITEM), SUM(TOTAL)
FROM SALES S
GROUP BY 1
ORDER BY 2, 3
;
--DIAGEOS TOP SELLING PRODUCTS
SELECT DESCRIPTION, SUM(TOTAL), COUNT(*)
FROM SALES
GROUP BY 1, VENDOR
HAVING VENDOR ILIKE '%DIAGEO%'
ORDER BY 2, 3
;
SELECT DESCRIPTION, SUM(TOTAL), COUNT(*)
FROM SALES
WHERE DESCRIPTION ILIKE '%SEAGRAMS%'
GROUP BY 1, VENDOR
HAVING VENDOR ILIKE '%DIAGEO%'
ORDER BY 2, 3
;
--TOP ITEMS
SELECT CATEGORY, COUNT(DISTINCT DESCRIPTION)
FROM SALES
GROUP BY 1
ORDER BY 2
;